# Generated by Django 5.2.8 on 2025-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTheater',
            fields=[
                ('number', models.PositiveSmallIntegerField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(max_length=50)),
                ('row', models.PositiveSmallIntegerField(max_length=20)),
            ],
            options={
                'unique_together': {('number', 'row')},
            },
        ),
    ]
