# Generated by Django 5.2.8 on 2025-12-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietheater',
            name='number',
            field=models.PositiveIntegerField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
