# Generated by Django 5.2.8 on 2025-12-14 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheaters', '0002_alter_movietheater_number_alter_seat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietheater',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
