# Generated by Django 5.2.8 on 2026-01-16 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheaters', '0003_alter_movietheater_number_alter_seat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movietheater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movietheaters.movietheater'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
