# Generated by Django 5.2.8 on 2026-01-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietheaters', '0004_seat_movietheater_alter_seat_row'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('number', 'row', 'movietheater')},
        ),
    ]
